'use client';

import { useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import Image from 'next/image';
import { FaArrowRight, FaBatteryFull, FaCalculator, FaCheckCircle, FaHome, FaLeaf, FaSolarPanel, FaTools } from 'react-icons/fa';
import SolarCalculator from '@/components/SolarCalculator';
import { useCart } from '@/contexts/CartContext';
import toast from 'react-hot-toast';

export default function HomePage() {
  const searchParams = useSearchParams();
  const { applyAffiliateCode, state } = useCart();
  const [monthlyBill, setMonthlyBill] = useState('150');
  const [homeType, setHomeType] = useState('Single Family Home');
  const [zipCode, setZipCode] = useState('84095');
  const [estimate, setEstimate] = useState({ payback: '3.6', savings: '$420', cost: '$18,200' });

  // Check for affiliate code in URL
  useEffect(() => {
    const affiliateCode = searchParams.get('ref');
    if (affiliateCode && !state.affiliateCode) {
      handleAffiliateCode(affiliateCode);
    }
  }, [searchParams, state.affiliateCode]);

  const handleAffiliateCode = async (code: string) => {
    try {
      const response = await fetch(`/api/public/affiliate-codes/${code}`);
      if (response.ok) {
        const data = await response.json();
        applyAffiliateCode(data.affiliateCode);
        toast.success(`Discount code "${code}" applied!`);
      } else {
        console.warn('Invalid affiliate code:', code);
      }
    } catch (error) {
      console.error('Error applying affiliate code:', error);
    }
  };

  const calculateQuickEstimate = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const bill = Math.max(50, Number(monthlyBill) || 150);
    const savings = Math.round(bill * 2.8);
    const cost = Math.round((bill * 42) / 100) * 100;
    setEstimate({ payback: (cost / (savings * 12)).toFixed(1), savings: `$${savings.toLocaleString()}`, cost: `$${cost.toLocaleString()}` });
  };

  return (
    <div className="flex min-h-screen flex-col bg-[#f8faf8] text-slate-800">
      <section className="hero-sunrise relative overflow-hidden bg-white"><div className="mx-auto grid max-w-[1280px] items-center gap-10 px-6 py-12 md:grid-cols-[.9fr_1.1fr] md:px-10 md:py-16"><div className="relative z-10 max-w-[560px]"><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-green-700 md:text-sm">Power with a purpose</p><h1 className="mb-5 max-w-[560px] text-5xl font-extrabold leading-[.98] tracking-tight text-[#073c32] sm:text-6xl">Solar that pays you back sooner.</h1><p className="mb-8 max-w-[520px] text-base leading-relaxed text-slate-600 md:text-lg">Affordable solar equipment plus expert installation, built around a 3-5 year payoff goal. Lower energy bills, more financial freedom, and a cleaner Utah for generations to come.</p><div className="flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-md bg-green-600 px-6 py-3 font-bold text-white shadow-lg shadow-green-600/20 transition hover:bg-green-700">Build My Solar Plan <FaArrowRight /></Link><Link href="/products" className="inline-flex items-center justify-center gap-2 rounded-md border-2 border-green-600 px-6 py-3 font-bold text-green-700 transition hover:bg-green-50">Shop Solar Kits</Link></div><div className="mt-9 grid max-w-[520px] grid-cols-3 gap-4 border-t border-slate-200 pt-5 text-xs font-semibold leading-tight text-slate-600"><span><FaTools className="mb-2 text-lg text-green-600" />DIY or Turnkey</span><span><FaCheckCircle className="mb-2 text-lg text-green-600" />Transparent pricing</span><span><FaHome className="mb-2 text-lg text-green-600" />Local Utah team</span></div></div><div className="relative h-[300px] md:h-[420px]"><div className="absolute -right-16 top-0 h-full w-[115%] overflow-hidden rounded-l-[45%] md:rounded-l-[48%]"><Image src="/images/mountain_home.jpg" alt="Solar home with Utah mountains in the background" fill priority className="object-cover object-center" sizes="(max-width: 768px) 100vw, 60vw" /></div><div className="absolute bottom-5 right-4 rounded-full bg-white/90 px-4 py-2 text-sm font-semibold text-[#075b42] shadow-lg">A brighter Utah, together</div></div></div></section>
      <section className="relative z-10 -mt-4 px-4 pb-10"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-lg bg-white shadow-[0_12px_40px_rgba(10,50,35,.12)] md:grid-cols-[1.25fr_.75fr]"><form onSubmit={calculateQuickEstimate} className="p-6 md:p-8"><div className="mb-6 flex items-start gap-3"><FaCalculator className="mt-1 text-2xl text-green-600" /><div><h2 className="text-2xl font-extrabold text-[#0b2330] md:text-3xl">See your solar payoff in 30 seconds</h2><p className="mt-1 text-sm text-slate-500">A quick estimate based on your home and monthly electric bill.</p></div></div><div className="grid gap-4 sm:grid-cols-3"><label className="text-xs font-bold text-slate-600">Your monthly bill<input value={monthlyBill} onChange={(event) => setMonthlyBill(event.target.value)} type="number" min="50" className="mt-2 w-full rounded border border-slate-300 px-3 py-3 text-base font-semibold" /></label><label className="text-xs font-bold text-slate-600">Your home type<select value={homeType} onChange={(event) => setHomeType(event.target.value)} className="mt-2 w-full rounded border border-slate-300 bg-white px-3 py-3 text-sm font-semibold"><option>Single Family Home</option><option>Townhome</option><option>Commercial</option></select></label><label className="text-xs font-bold text-slate-600">Your ZIP code<input value={zipCode} onChange={(event) => setZipCode(event.target.value)} className="mt-2 w-full rounded border border-slate-300 px-3 py-3 text-base font-semibold" /></label></div><div className="mt-6 flex flex-wrap items-center gap-4"><button type="submit" className="inline-flex items-center gap-2 rounded-md bg-green-600 px-6 py-3 font-bold text-white hover:bg-green-700">Calculate my savings <FaArrowRight /></button><span className="text-xs text-slate-500">No personal information needed.</span></div></form><div className="bg-[#eaf7f0] p-6 md:p-8"><p className="text-sm font-semibold text-slate-600">Estimated payback period</p><p className="my-2 text-5xl font-extrabold text-green-600">{estimate.payback} <span className="text-2xl">years</span></p><div className="h-3 rounded-full bg-slate-200"><div className="h-full w-3/4 rounded-full bg-green-500" /></div><div className="mt-7 grid grid-cols-3 gap-3 border-t border-green-900/10 pt-5 text-sm"><span><strong className="block text-base text-slate-800">{estimate.cost}</strong>Estimated cost</span><span><strong className="block text-base text-slate-800">{estimate.savings}</strong>Monthly savings</span><span><strong className="block text-base text-slate-800">{zipCode}</strong>Service area</span></div></div></div></section>
      <section className="mx-auto w-full max-w-6xl px-4 pb-14"><div className="grid gap-5 md:grid-cols-2">{[{ icon: FaHome, image: '/images/installer.jpg', title: 'We install it', kicker: 'Full-service solar installation', copy: 'Let our local Utah team handle everything from design and permitting to professional installation and grid connection.', href: '/contact', cta: 'Get a free installation quote' }, { icon: FaSolarPanel, image: '/images/kit.jpg', title: 'You build it', kicker: 'DIY solar kits', copy: 'Buy high-quality solar equipment at transparent prices and install it yourself. We help you choose the right system and provide ongoing support.', href: '/products', cta: 'Shop solar kits' }].map((path) => <article key={path.title} className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm"><div className="relative h-48"><Image src={path.image} alt={path.title} fill className="object-cover" sizes="(max-width: 768px) 100vw, 50vw" /></div><div className="p-6"><div className="flex items-center gap-3"><path.icon className="text-3xl text-green-600" /><div><h3 className="text-2xl font-extrabold text-[#0b2330]">{path.title}</h3><p className="text-sm font-bold text-green-700">{path.kicker}</p></div></div><p className="my-4 text-sm leading-relaxed text-slate-600">{path.copy}</p><div className="mb-5 grid grid-cols-3 gap-2 text-center text-xs text-slate-500"><span><b className="mx-auto mb-1 flex h-7 w-7 items-center justify-center rounded-full bg-green-600 text-white">1</b>Choose your path</span><span><b className="mx-auto mb-1 flex h-7 w-7 items-center justify-center rounded-full bg-green-600 text-white">2</b>Get guidance</span><span><b className="mx-auto mb-1 flex h-7 w-7 items-center justify-center rounded-full bg-green-600 text-white">3</b>Start saving</span></div><Link href={path.href} className="inline-flex w-full items-center justify-center gap-2 rounded-md border-2 border-green-600 px-4 py-2 font-bold text-green-700 hover:bg-green-50">{path.cta} <FaArrowRight /></Link></div></article>)}</div></section>
      <section className="bg-[#eff8f2] py-12"><div className="mx-auto max-w-6xl px-4"><div className="mb-7 flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[.15em] text-green-700">Why Payoff Solar</p><h2 className="mt-1 text-3xl font-extrabold text-[#0b2330]">A smarter way to go solar.</h2></div><p className="max-w-md text-sm text-slate-600">We make clean energy accessible, affordable, and hassle-free, with a focus on real financial returns.</p></div><div className="grid gap-4 md:grid-cols-3">{[[FaSolarPanel, 'Direct equipment access', 'Get high-quality equipment at a better price.'], [FaLeaf, 'Designed to pay off', 'Systems designed around strong financial returns.'], [FaBatteryFull, 'Flexible project support', 'Full-service or DIY support that fits your goals.']].map(([Icon, title, copy]) => <div key={title as string} className="flex gap-4 rounded-md bg-white p-5"><Icon className="mt-1 shrink-0 text-3xl text-green-600" /><div><h3 className="font-extrabold text-[#0b2330]">{title as string}</h3><p className="mt-1 text-sm text-slate-600">{copy as string}</p></div></div>)}</div></div></section>
      <section className="py-14"><div className="mx-auto max-w-6xl px-4"><div className="flex items-center justify-between"><h2 className="text-3xl font-extrabold text-[#0b2330]">Popular solar products</h2><Link href="/products" className="text-sm font-bold text-green-700">View all products <FaArrowRight className="ml-1 inline" /></Link></div><div className="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">{[['/images/solar_panels.jpg', 'Solar panels', 'High-efficiency panels'], ['/images/batteries.jpg', 'Batteries', 'Keep power on'], ['/images/inverter.jpg', 'Inverters', 'Reliable performance'], ['/images/mounting.jpg', 'Mounting', 'Durable solutions']].map(([image, title, copy]) => <Link href="/products" key={title} className="group overflow-hidden rounded-md border border-slate-200 bg-white"><div className="relative h-28"><Image src={image} alt={title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="25vw" /></div><div className="p-4"><h3 className="font-extrabold capitalize text-[#0b2330]">{title}</h3><p className="mt-1 text-xs text-slate-500">{copy}</p><span className="mt-3 block text-xs font-bold text-green-700">Shop {title} <FaArrowRight className="ml-1 inline" /></span></div></Link>)}</div></div></section>
      <section className="bg-[#075b42] py-12 text-white"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 px-4 md:flex-row md:items-center"><div><h2 className="text-3xl font-extrabold">Ready to make solar pay off?</h2><p className="mt-2 max-w-xl text-sm text-white/80">Join Utah homeowners taking control of their energy bills with a smarter path to solar.</p></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/contact" className="rounded-md bg-green-500 px-5 py-3 text-center font-bold text-white hover:bg-green-400">Build my solar plan <FaArrowRight className="ml-1 inline" /></Link><Link href="/products" className="rounded-md border border-white/60 px-5 py-3 text-center font-bold text-white hover:bg-white/10">Shop solar kits</Link></div></div></section>
      <section className="bg-white px-4 py-8"><div className="mx-auto max-w-6xl"><details><summary className="flex cursor-pointer items-center gap-2 font-bold text-[#0b2330]"><FaCalculator className="text-green-600" /> Need a detailed system builder?</summary><div className="mt-6"><SolarCalculator /></div></details></div></section>
    </div>
  );
}
